<?php 
    $data_LP1 = array(
                    "url_qr_code" => "url image",
                    "nom_prenom_titu" => array("val" => "ANDRIAMASINAVALONA davidson",
                                            "X" => 67,
                                            "Y" => 113),
                    "type_permis_titu" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 118),
                    "numero_titu" => array("val" => "test enjana mety ve",
                                            "X" => 67,
                                            "Y" => 123),
                    "type_prod" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 141),
                    "substance" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 146),
                    "qtt_chiffre" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 151),
                    "qtt_lettre" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 156),
                    "commune_orig" => array("val" => "test enjana",
                                            "X" => 50,
                                            "Y" => 180),
                    "commune_dest" => array("val" => "test enjana",
                                            "X" => 90,
                                            "Y" => 180),
                    "distric_orig" => array("val" => "test enjana",
                                            "X" => 50,
                                            "Y" => 190),
                    "distric_dest" => array("val" => "test enjana",
                                            "X" => 90,
                                            "Y" => 190),
                    "region_orig" => array("val" => "test enjana",
                                            "X" => 50,
                                            "Y" => 200),
                    "region_dest" => array("val" => "test enjana",
                                            "X" => 90,
                                            "Y" => 200),
                    "nom_prenom_conv" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 218.5),
                    "cin_conv" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 223.5),
                    "date_fait" => array("val" => "test enjana",
                                            "X" => 142,
                                            "Y" => 236.5),
                    "date_arriv" => array("val" => "test enjana",
                                            "X" => 142,
                                            "Y" => 190),
                                            
                    );
    $data_LP2 = array();
    $data_LP3C = array();
    $data_LP3E = array();
?>