<?php 
    $data_LP1 = array(
                    "url_qr_code" => "url image",
                    "nom_prenom_titu" => array("val" => "ANDRIAMASINAVALONA davidson",
                                            "X" => 67,
                                            "Y" => 113),
                    "type_permis_titu" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 118),
                    "numero_titu" => array("val" => "test enjana mety ve",
                                            "X" => 67,
                                            "Y" => 123),
                    "type_prod" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 141),
                    "substance" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 146),
                    "qtt_chiffre" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 151),
                    "qtt_lettre" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 156),
                    "commune_orig" => array("val" => "test enjana",
                                            "X" => 50,
                                            "Y" => 180),
                    "commune_dest" => array("val" => "test enjana",
                                            "X" => 90,
                                            "Y" => 180),
                    "distric_orig" => array("val" => "test enjana",
                                            "X" => 50,
                                            "Y" => 190),
                    "distric_dest" => array("val" => "test enjana",
                                            "X" => 90,
                                            "Y" => 190),
                    "region_orig" => array("val" => "test enjana",
                                            "X" => 50,
                                            "Y" => 200),
                    "region_dest" => array("val" => "test enjana",
                                            "X" => 90,
                                            "Y" => 200),
                    "nom_prenom_conv" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 218.5),
                    "cin_conv" => array("val" => "test enjana",
                                            "X" => 67,
                                            "Y" => 223.5),
                    "date_fait" => array("val" => "test enjana",
                                            "X" => 142,
                                            "Y" => 236.5),
                    "date_arriv" => array("val" => "test enjana",
                                            "X" => 142,
                                            "Y" => 190),
                                            
                    );
    $data_LP2 = array(
        "url_qr_code" => "url image",
        "nom_prenom_trans" => array("val" => "ANDRIAMASINAVALONA davidson",
                                "X" => 67,
                                "Y" => 113),
        "type_autorisation_trans" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 118),
        "numero_trans" => array("val" => "test enjana mety ve",
                                "X" => 67,
                                "Y" => 123),
        "date_trans" => array("val" => "test enjana mety ve",
                                "X" => 67,
                                "Y" => 128),

        "type_prod" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 146),
        "substance" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 151),
        "qtt_chiffre" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 156),
        "qtt_lettre" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 161),

        "commune_orig" => array("val" => "test enjana",
                                "X" => 50,
                                "Y" => 190),
        "commune_dest" => array("val" => "test enjana",
                                "X" => 90,
                                "Y" => 190),

        "distric_orig" => array("val" => "test enjana",
                                "X" => 50,
                                "Y" => 200),
        "distric_dest" => array("val" => "test enjana",
                                "X" => 90,
                                "Y" => 200),

        "region_orig" => array("val" => "test enjana",
                                "X" => 50,
                                "Y" => 210),
        "region_dest" => array("val" => "test enjana",
                                "X" => 90,
                                "Y" => 210),

        "nom_prenom_conv" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 228),
        "cin_conv" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 233),

        "date_fait" => array("val" => "test enjana",
                                "X" => 142,
                                "Y" => 246),
        "date_arriv" => array("val" => "test enjana",
                                "X" => 142,
                                "Y" => 200),
                                
        );
    $data_LP3C = array(
        "url_qr_code" => "url image",
        "nom_prenom_trans" => array("val" => "ANDRIAMASINAVALONA davidson",
                                "X" => 67,
                                "Y" => 113),
        "type_autorisation_trans" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 118),
        "numero_trans" => array("val" => "test enjana mety ve",
                                "X" => 67,
                                "Y" => 123),
        "date_trans" => array("val" => "test enjana mety ve",
                                "X" => 67,
                                "Y" => 128),

        "type_prod" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 146),
        "categorie_prod" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 151),
        "substance" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 156),
        "qtt_chiffre" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 161),
        "qtt_lettre" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 166),

        "commune_orig" => array("val" => "test enjana",
                                "X" => 50,
                                "Y" => 200),
        "commune_dest" => array("val" => "test enjana",
                                "X" => 90,
                                "Y" => 200),

        "distric_orig" => array("val" => "test enjana",
                                "X" => 50,
                                "Y" => 210),
        "distric_dest" => array("val" => "test enjana",
                                "X" => 90,
                                "Y" => 210),

        "region_orig" => array("val" => "test enjana",
                                "X" => 50,
                                "Y" => 220),
        "region_dest" => array("val" => "test enjana",
                                "X" => 90,
                                "Y" => 220),

        "nom_prenom_conv" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 238),
        "cin_conv" => array("val" => "test enjana",
                                "X" => 67,
                                "Y" => 243),

        "date_fait" => array("val" => "test enjana",
                                "X" => 142,
                                "Y" => 255),
        "date_arriv" => array("val" => "test enjana",
                                "X" => 142,
                                "Y" => 210),
                                
        );
    $data_LP3E = array(
        "nom_prenom" => array("val" => "ANDRIAMASINAVALONA davidson",
                                "X" => 67,
                                "Y" => 121),
        "type" => array("val" => "test",
                                "X" => 67,
                                "Y" => 127),
        "nom_prenom" => array("val" => "ANDRIAMASINAVALONA davidson",
                                "X" => 67,
                                "Y" => 121),
    );
?>